name: "Build Promo Video English"

on: workflow_dispatch

jobs:
  promo-video-en:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Installing unzip
        run: sudo apt-get install -y unzip
      - name: Unzipping the promo-video-en.zip file
        run: unzip promo-video-en.zip -d tmpfolder20220805
      - name: Checking if a VideoMaker configuration exists
        run: |
             if [ $(wc -c <"./tmpfolder20220805/promo-video-en/input_video.cfg") -ge 5 ]
               then
                 echo "VideoMaker configuration file found."
               else
                 echo "VideoMaker configuration file not found."
                 exit 1
             fi
      - name: Installing ffmpeg
        run: sudo apt-get install -y ffmpeg
      - name: Making the VideoMaker script executable
        run: chmod +x ./.github/workflows/videomaker.sh
      - name: Creating the video file
        run: cd tmpfolder20220805/promo-video-en && ../../.github/workflows/videomaker.sh && cp output.mp4 promo-video-en.mp4
      - name: Attaching the created video this workflow
        uses: actions/upload-artifact@v3
        with:
          name: promo-video-en
          path: tmpfolder20220805/promo-video-en/promo-video-en.mp4
